<?php

namespace ModuleBZ\SchemaOrg\Traits\Thing\Intangible;

use ModuleBZ\SchemaOrg\DataType\Text;
trait TService{
	 /**
	 * The overall rating, based on a collection of reviews or ratings, of the item.
	 * @var String $aggregateRating
	 */
	protected $aggregateRating;

	 /**
	 * The geographic area where a service or offered item is provided. Supersedes <a href="/serviceArea">serviceArea</a>.
	 * @var String $areaServed
	 */
	protected $areaServed;

	 /**
	 * An intended audience, i.e. a group for whom something was created. Supersedes <a href="/serviceAudience">serviceAudience</a>.
	 * @var String $audience
	 */
	protected $audience;

	 /**
	 * A means of accessing the service (e.g. a phone bank, a web site, a location, etc.).
	 * @var String $availableChannel
	 */
	protected $availableChannel;

	 /**
	 * An award won by or for this item. Supersedes <a href="/awards">awards</a>.
	 * @var String $award
	 */
	protected $award;

	 /**
	 * The brand(s) associated with a product or service, or the brand(s) maintained by an organization or business person.
	 * @var String $brand
	 */
	protected $brand;

	 /**
	 * An entity that arranges for an exchange between a buyer and a seller.  In most cases a broker never acquires or releases ownership of a product or service involved in an exchange.  If it is not clear whether an entity is a broker, seller, or buyer, the latter two terms are preferred. Supersedes <a href="/bookingAgent">bookingAgent</a>.
	 * @var String $broker
	 */
	protected $broker;

	 /**
	 * A category for the item. Greater signs or slashes can be used to informally indicate a category hierarchy.
	 * @var String $category
	 */
	protected $category;

	 /**
	 * Indicates an OfferCatalog listing for this Organization, Person, or Service.
	 * @var String $hasOfferCatalog
	 */
	protected $hasOfferCatalog;

	 /**
	 * The hours during which this service or contact is available.
	 * @var String $hoursAvailable
	 */
	protected $hoursAvailable;

	 /**
	 * A pointer to another, somehow related product (or multiple products).
	 * @var String $isRelatedTo
	 */
	protected $isRelatedTo;

	 /**
	 * A pointer to another, functionally similar product (or multiple products).
	 * @var String $isSimilarTo
	 */
	protected $isSimilarTo;

	 /**
	 * An associated logo.
	 * @var String $logo
	 */
	protected $logo;

	 /**
	 * An offer to provide this item—for example, an offer to sell a product, rent the DVD of a movie, perform a service, or give away tickets to an event. Use <a class="localLink" href="/businessFunction">businessFunction</a> to indicate the kind of transaction offered, i.e. sell, lease, etc. This property can also be used to describe a <a class="localLink" href="/Demand">Demand</a>. While this property is listed as expected on a number of common types, it can be used in others. In that case, using a second type, such as Product or a subtype of Product, can clarify the nature of the offer.<br> Inverse property: <a href="/itemOffered">itemOffered</a>.
	 * @var String $offers
	 */
	protected $offers;

	 /**
	 * The service provider, service operator, or service performer; the goods producer. Another party (a seller) may offer those services or goods on behalf of the provider. A provider may also serve as the seller. Supersedes <a href="/carrier">carrier</a>.
	 * @var String $provider
	 */
	protected $provider;

	 /**
	 * Indicates the mobility of a provided service (e.g. 'static', 'dynamic').
	 * @var String $providerMobility
	 */
	protected $providerMobility;

	 /**
	 * A review of the item. Supersedes <a href="/reviews">reviews</a>.
	 * @var String $review
	 */
	protected $review;

	 /**
	 * The tangible thing generated by the service, e.g. a passport, permit, etc. Supersedes <a href="/produces">produces</a>.
	 * @var String $serviceOutput
	 */
	protected $serviceOutput;

	 /**
	 * The type of service being offered, e.g. veterans' benefits, emergency relief, etc.
	 * @var String $serviceType
	 */
	protected $serviceType;

	 /**
	 * A slogan or motto associated with the item.
	 * @var String $slogan
	 */
	protected $slogan;

	 /**
	 * Human-readable terms of service documentation.
	 * @var String $termsOfService
	 */
	protected $termsOfService;


	/**
	 * @param $x
	 * @return $this
	 */
	public function setAggregateRating($x){
		$this->aggregateRating = new Text('AggregateRating',$x);
		return $this;
	}

	/**
	 * @param $x
	 * @return $this
	 */
	public function setAreaServed($x){
		$this->areaServed = new Text('AreaServed',$x);
		return $this;
	}

	/**
	 * @param $x
	 * @return $this
	 */
	public function setAudience($x){
		$this->audience = new Text('Audience',$x);
		return $this;
	}

	/**
	 * @param $x
	 * @return $this
	 */
	public function setAvailableChannel($x){
		$this->availableChannel = new Text('AvailableChannel',$x);
		return $this;
	}

	/**
	 * @param $x
	 * @return $this
	 */
	public function setAward($x){
		$this->award = new Text('Award',$x);
		return $this;
	}

	/**
	 * @param $x
	 * @return $this
	 */
	public function setBrand($x){
		$this->brand = new Text('Brand',$x);
		return $this;
	}

	/**
	 * @param $x
	 * @return $this
	 */
	public function setBroker($x){
		$this->broker = new Text('Broker',$x);
		return $this;
	}

	/**
	 * @param $x
	 * @return $this
	 */
	public function setCategory($x){
		$this->category = new Text('Category',$x);
		return $this;
	}

	/**
	 * @param $x
	 * @return $this
	 */
	public function setHasOfferCatalog($x){
		$this->hasOfferCatalog = new Text('HasOfferCatalog',$x);
		return $this;
	}

	/**
	 * @param $x
	 * @return $this
	 */
	public function setHoursAvailable($x){
		$this->hoursAvailable = new Text('HoursAvailable',$x);
		return $this;
	}

	/**
	 * @param $x
	 * @return $this
	 */
	public function setIsRelatedTo($x){
		$this->isRelatedTo = new Text('IsRelatedTo',$x);
		return $this;
	}

	/**
	 * @param $x
	 * @return $this
	 */
	public function setIsSimilarTo($x){
		$this->isSimilarTo = new Text('IsSimilarTo',$x);
		return $this;
	}

	/**
	 * @param $x
	 * @return $this
	 */
	public function setLogo($x){
		$this->logo = new Text('Logo',$x);
		return $this;
	}

	/**
	 * @param $x
	 * @return $this
	 */
	public function setOffers($x){
		$this->offers = new Text('Offers',$x);
		return $this;
	}

	/**
	 * @param $x
	 * @return $this
	 */
	public function setProvider($x){
		$this->provider = new Text('Provider',$x);
		return $this;
	}

	/**
	 * @param $x
	 * @return $this
	 */
	public function setProviderMobility($x){
		$this->providerMobility = new Text('ProviderMobility',$x);
		return $this;
	}

	/**
	 * @param $x
	 * @return $this
	 */
	public function setReview($x){
		$this->review = new Text('Review',$x);
		return $this;
	}

	/**
	 * @param $x
	 * @return $this
	 */
	public function setServiceOutput($x){
		$this->serviceOutput = new Text('ServiceOutput',$x);
		return $this;
	}

	/**
	 * @param $x
	 * @return $this
	 */
	public function setServiceType($x){
		$this->serviceType = new Text('ServiceType',$x);
		return $this;
	}

	/**
	 * @param $x
	 * @return $this
	 */
	public function setSlogan($x){
		$this->slogan = new Text('Slogan',$x);
		return $this;
	}

	/**
	 * @param $x
	 * @return $this
	 */
	public function setTermsOfService($x){
		$this->termsOfService = new Text('TermsOfService',$x);
		return $this;
	}


}